### ISSUE TITLE
为什么这么做

### ISSUE THREAD

**Issue by wuxinheng** [meaglecyen/MWinNet#1]
不太能理解这个框架可以做什么

**Comment by wiome0x** [comment]
在传统的 WPF 应用程序中，所有页面和业务逻辑通常都在一个可执行文件中，这意味着如果需要修改任何部分，就必须重新构建整个解决方案。通过使用 OSGi.NET，可以将应用程序分成多个小模块，每个模块可以独立开发、测试和部署。
